apiVersion: apps/v1
kind: Deployment
metadate:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 3
  template:
    metadate:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: myusername/gateway
          envFrom:
            - configMapRef:
              name: gateway-configmap
            - secretRef:
              name: gateway-secret